### ISSUE TITLE
Rename /web to /en for English

### ISSUE THREAD

**Issue by instafluff** [instafluff/ComfyDictionary#4]
The English dictionary needs to be in the /en folder instead of /web

**Comment by SoffiMeower** [comment]
I can do this.

**Comment by instafluff** [comment]
That will be great!

**Comment by SoffiMeower** [comment]
My PC is suffering with the 100000 different files it has to unzip lol.

**Comment by SoffiMeower** [comment]
Impossible: Chrome crashes when trying to put files into EN folder on github.

**Comment by instafluff** [comment]
Oh jeez. I had to play around with Git to get it to correctly push all those files originally. I guess GitHub might not like changing existing files either...
